# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88f4abae82a5dff850b9ca169e02a9e3e9a50c30c2002bfc999d34d6768455ab44fa71a976d96f55a20a857e2dd66766615a21c082bd1506436827236d5849a2

test:
  secret_key_base: b31fd7ec9a079ed8c2921286825259e6850ca55dca11cb225d6cad82dd08c04f627f8fb1910bc0638a82236e8fd609203f639e776487ac69a6a2b921705013e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
